# Simulation to run with ns-3
target = "elora-example"

# Arguments to pass to the simulation.
[args]

# Number of periods to simulate (1 period = 1 hour)
periods = 24

# Number of gateway rings to instantiate using hexagonal topology
#   
#   1 = 1 gateway
#   2 = 7 gateways
#   3 = 19 gateways
#   ...
#
rings = 1

# Radius of the device allocation disk around a gateway
# (range * 2 = gateway distance)
range = 2540.25

# Number of end devices to include in the simulation
devices = 1

# Signal to Interference Ratio matrix used for interference
# 
# Options: [CROCE, GOURSAUD, ALHOA]
#
sir = "CROCE"

# Whether to pre-initialize the SFs of devices before starting the sumulation
# (uses a conservative version of the default ADR algorithm, without power management)
initSF = true

# Whether to enable the ADR bit 
adr = true

# Use test devices (5s period, 5B payload) instead of realistic urban M2M traffic
test = true

# Whether to enable .pcap tracing on gateways
file = true

# Whether to enable detailed logs on the devices' MAC layer,
# and simple logs on UDP traffic in gateways
log = true

# Seed to use in the random generation engine of ns-3
RngRun = 0
