######################### ELoRa example configuration file #########################
#
# This file is used to specify which simulation target will be run by ns-3
# (for instance, see elora-example.cc) as well as the parameters to pass to
# the simulation.
#
# Any setting other than the 'target' needs to be exposed in advance 
# using cmd.AddValue(...) in the main .cc file.
#

# Required simulation target to run with ns-3.
# Simulation files are to be loaded as a volume in docker-compose.yml
target = "elora-example"

# Arguments to pass to the simulation.
[args]

# These are specific to the implementation (elora-example.cc in this case)
#
# Note: the following part of the configuration file exists only to improve 
#  quality of life, all this settings could be set directly in the main .cc file.

    # Chirpstack tenant that will be associated to this ELoRa instance
    tenant = "ELoRa"

    # Chirpstack REST API endpoint IP address (port is default 8090)
    api = "127.0.0.1"

    # Chirpstack API token (this needs to be generated in Chirpstack and copy-pasted here)
    token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6IjZlMjQ4NjljLWQxMjItNDZkOS04NzE0LTM5Yzc4Nzg4OTRhZCIsInR5cCI6ImtleSJ9.IB20o6Jrcwj5qZ9mPEuthzzqMyc3YNSl8by_ZXrjqhw"

    # Number of periods to simulate (1 period = 1 hour)
    periods = 24

    # Number of gateway rings to instantiate using hexagonal topology
    #   
    #   1 = 1 gateway
    #   2 = 7 gateways
    #   3 = 19 gateways
    #   ...
    #
    rings = 1

    # Radius of the device allocation disk around a gateway
    # (range * 2 = gateway distance)
    range = 2540.25

    # Number of end devices to include in the simulation
    devices = 1

    # Signal to Interference Ratio matrix used for interference
    # 
    # Options: [CROCE, GOURSAUD, ALHOA]
    #
    sir = "CROCE"

    # Whether to pre-initialize the SFs of devices before starting the sumulation
    # (uses a conservative version of the default ADR algorithm, without power management)
    initSF = true

    # Whether to enable the ADR bit 
    adr = true

    # Use test devices (5s period, 5B payload) instead of realistic urban M2M traffic
    test = true

    # Whether to enable .pcap tracing on gateways
    file = true

    # Whether to enable detailed logs on the devices' MAC layer,
    # and simple logs on UDP traffic in gateways
    log = true

    # Seed to use in the random generation engine of ns-3
    RngRun = 0
