version: "0.1"

services:
  elora:
    image: 10.31.81.1:5000/local/elora:0.3
    build: ./build
    network_mode: "bridge"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./configuration.toml:/home/elora/configuration.toml
      - ./elora-example:/home/elora/ns-3-dev/scratch/elora-example
      - ./data:/home/elora/data
