apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elora-statefulset.yaml

configMapGenerator:
  - name: elora-config-cm
    files:
      - configuration.toml
  - name: elora-example-cm
    files:
      - elora-example-utilities.h
      - elora-example.cc
      - elora-example-utilities.cc